import {
  UserProfile,
  Complaint,
  GatePass,
  AttendanceRecord,
  MarksRecord,
  FeeBreakdown,
  FeeSummary,
  PaymentTransaction,
  TimetableEntry,
  CertificateRequest,
  CampusNotice,
  NotificationItem,
  CampusIncident,
  CampusEvent,
  LeaveRequest,
  RefundRequest,
  AwardItem,
} from '@/types';

export const initialProfiles: Record<string, UserProfile> = {
  student: {
    id: 'usr_std_25107',
    name: 'Ashwanth R',
    role: 'student',
    email: 'ashwanth.r@campusone.edu.in',
    phone: '+91 98450 12345',
    rollNo: '25107',
    department: 'Department of Cyber Security',
    program: 'B.Tech Cyber Security',
    year: '2nd Year',
    semester: 'Semester 4',
    hostel: 'Agastya Bhavan, Room 304',
    bloodGroup: 'O+ Positive',
    emergencyContact: '+91 94432 67890 (Father - Mr. R. Ramesh)',
  },
  faculty: {
    id: 'usr_fac_001',
    name: 'Dr. Priya Menon',
    role: 'faculty',
    email: 'priya.menon@campusone.edu.in',
    phone: '+91 98401 55678',
    facultyId: 'FAC001',
    designation: 'Associate Professor & Class Advisor',
    department: 'Computer Science',
    cabin: 'Academic Block 2, Cabin 204',
  },
  admin: {
    id: 'usr_adm_001',
    name: 'Administrator',
    role: 'admin',
    email: 'admin@campusone.edu.in',
    phone: '+91 422 268 5000',
    adminId: 'ADMIN001',
    officeTitle: 'Administration Portal',
    department: 'Central Administration Desk',
  },
};

export const initialComplaints: Complaint[] = [
  {
    id: 'CMP-1024',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    category: 'Hostel',
    title: 'Hostel Wi-Fi not working',
    description: 'Internet connection is completely unavailable on 3rd floor East wing (Agastya Bhavan). High packet drop since yesterday.',
    priority: 'Medium',
    status: 'In Progress',
    assignedDepartment: 'IT Support Services',
    assignedStaff: 'K. Senthil (Network Engineer)',
    createdAt: '25 Sep 2026, 09:30 AM',
    updatedAt: '25 Sep 2026, 02:15 PM',
    steps: [
      {
        title: 'Submitted by Student',
        timestamp: '25 Sep 2026, 09:30 AM',
        actor: 'Ashwanth R',
        note: 'Issue logged via Student Portal',
        status: 'completed',
      },
      {
        title: 'Assigned to IT Department',
        timestamp: '25 Sep 2026, 11:00 AM',
        actor: 'Admin Helpdesk',
        note: 'Ticket routed to Campus Network Operation Center',
        status: 'completed',
      },
      {
        title: 'Technician Working',
        timestamp: '25 Sep 2026, 02:15 PM',
        actor: 'K. Senthil (Network Engg)',
        note: 'Access point AP-3E rebooted; fiber uplink being inspected.',
        status: 'current',
      },
      {
        title: 'Resolution Verification',
        timestamp: 'Pending verification',
        status: 'upcoming',
      },
      {
        title: 'Ticket Closed',
        timestamp: 'Pending closure',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'CMP-1018',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    category: 'Infrastructure',
    title: 'Lab 4 Projector flickering in CS Block',
    description: 'The HDMI connection flickers intermittently during lectures.',
    priority: 'Low',
    status: 'Resolved',
    assignedDepartment: 'Audio-Visual Media Center',
    assignedStaff: 'P. Anand',
    createdAt: '18 Sep 2026, 10:15 AM',
    updatedAt: '20 Sep 2026, 04:00 PM',
    resolutionNotes: 'HDMI transmitter box replaced and tested with faculty laptop.',
    steps: [
      {
        title: 'Submitted by Student',
        timestamp: '18 Sep 2026, 10:15 AM',
        actor: 'Ashwanth R',
        status: 'completed',
      },
      {
        title: 'Assigned to AV Support',
        timestamp: '18 Sep 2026, 12:40 PM',
        actor: 'Admin Helpdesk',
        status: 'completed',
      },
      {
        title: 'Technician Working',
        timestamp: '19 Sep 2026, 02:00 PM',
        actor: 'P. Anand',
        status: 'completed',
      },
      {
        title: 'Resolution',
        timestamp: '20 Sep 2026, 04:00 PM',
        actor: 'P. Anand',
        note: 'Replaced transmitter cable.',
        status: 'completed',
      },
      {
        title: 'Ticket Closed',
        timestamp: '20 Sep 2026, 04:30 PM',
        actor: 'Ashwanth R (Feedback 5/5)',
        status: 'completed',
      },
    ],
  },
  {
    id: 'CMP-1029',
    studentName: 'Manoj Kumar',
    rollNo: '25114',
    category: 'Finance',
    title: 'Mess Fee adjustment for sports camp absence',
    description: 'Requested mess rebate for 10 days of University Athletics tournament attendance.',
    priority: 'Medium',
    status: 'Assigned',
    assignedDepartment: 'Finance & Accounts',
    assignedStaff: 'V. Ramanathan (Accounts Officer)',
    createdAt: '24 Sep 2026, 03:00 PM',
    updatedAt: '25 Sep 2026, 10:00 AM',
    steps: [
      {
        title: 'Submitted by Student',
        timestamp: '24 Sep 2026, 03:00 PM',
        actor: 'Manoj Kumar',
        status: 'completed',
      },
      {
        title: 'Assigned to Finance',
        timestamp: '25 Sep 2026, 10:00 AM',
        actor: 'Admin Helpdesk',
        status: 'current',
      },
      {
        title: 'In Verification',
        timestamp: 'Awaiting Physical Director approval',
        status: 'upcoming',
      },
      {
        title: 'Refund Credit',
        timestamp: 'Pending',
        status: 'upcoming',
      },
      {
        title: 'Closed',
        timestamp: 'Pending',
        status: 'upcoming',
      },
    ],
  },
];

export const initialGatePasses: GatePass[] = [
  {
    id: 'GP-890',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    date: '26 Sep 2026',
    outTime: '06:00 PM',
    expectedReturn: '09:00 PM',
    destination: 'Coimbatore Medical Center / Town Clinic',
    reason: 'Prescription refill and routine dental appointment',
    status: 'Pending',
    appliedOn: '26 Sep 2026, 08:30 AM',
  },
  {
    id: 'GP-881',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    date: '22 Sep 2026',
    outTime: '05:00 PM',
    expectedReturn: '08:30 PM',
    destination: 'Gandhipuram City Center',
    reason: 'Hardware components procurement for IoT lab project',
    status: 'Approved',
    appliedOn: '21 Sep 2026, 02:15 PM',
    approvedBy: 'Dr. Radhika M (Warden/Advisor)',
  },
  {
    id: 'GP-875',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    date: '15 Sep 2026',
    outTime: '06:30 PM',
    expectedReturn: '11:00 PM',
    destination: 'Local Cinema Complex',
    reason: 'Movie outing with classmates',
    status: 'Rejected',
    appliedOn: '15 Sep 2026, 11:00 AM',
    approvedBy: 'Hostel Chief Warden (Late curfew not permitted without parent mail)',
  },
];

export const initialAttendance: AttendanceRecord[] = [
  {
    subjectCode: '21CS201',
    subjectName: 'Cryptography & Network Security',
    faculty: 'Dr. Radhika M',
    totalClasses: 47,
    attendedClasses: 41,
    percentage: 87.2,
    isEligible: true,
  },
  {
    subjectCode: '21CS202',
    subjectName: 'Operating Systems & Kernels',
    faculty: 'Prof. K. Narayanan',
    totalClasses: 47,
    attendedClasses: 43,
    percentage: 91.5,
    isEligible: true,
  },
  {
    subjectCode: '21CS203',
    subjectName: 'Database Management Systems',
    faculty: 'Dr. S. Meenakshi',
    totalClasses: 45,
    attendedClasses: 37,
    percentage: 82.2,
    isEligible: true,
  },
  {
    subjectCode: '21CS204',
    subjectName: 'Web Technology & Modern Frameworks',
    faculty: 'Prof. Arjun V',
    totalClasses: 48,
    attendedClasses: 45,
    percentage: 93.8,
    isEligible: true,
  },
  {
    subjectCode: '21MA205',
    subjectName: 'Discrete Mathematics & Graph Theory',
    faculty: 'Dr. T. Venkatraman',
    totalClasses: 48,
    attendedClasses: 42,
    percentage: 87.5,
    isEligible: true,
  },
];

export const initialMarks: MarksRecord[] = [
  {
    subjectCode: '21CS201',
    subjectName: 'Cryptography & Network Security',
    internal: 42,
    internalMax: 50,
    assignment: 19,
    assignmentMax: 20,
    lab: 28,
    labMax: 30,
    endSem: 41,
    endSemMax: 50,
    total: 88,
    grade: 'A',
    credits: 4,
  },
  {
    subjectCode: '21CS202',
    subjectName: 'Operating Systems & Kernels',
    internal: 45,
    internalMax: 50,
    assignment: 18,
    assignmentMax: 20,
    lab: 29,
    labMax: 30,
    endSem: 46,
    endSemMax: 50,
    total: 92,
    grade: 'A+',
    credits: 4,
  },
  {
    subjectCode: '21CS203',
    subjectName: 'Database Management Systems',
    internal: 38,
    internalMax: 50,
    assignment: 17,
    assignmentMax: 20,
    lab: 26,
    labMax: 30,
    endSem: 39,
    endSemMax: 50,
    total: 81,
    grade: 'B+',
    credits: 4,
  },
  {
    subjectCode: '21CS204',
    subjectName: 'Web Technology & Modern Frameworks',
    internal: 48,
    internalMax: 50,
    assignment: 20,
    assignmentMax: 20,
    lab: 30,
    labMax: 30,
    endSem: 47,
    endSemMax: 50,
    total: 96,
    grade: 'O',
    credits: 4,
  },
  {
    subjectCode: '21MA205',
    subjectName: 'Discrete Mathematics & Graph Theory',
    internal: 43,
    internalMax: 50,
    assignment: 18,
    assignmentMax: 20,
    lab: 0,
    labMax: 0,
    endSem: 44,
    endSemMax: 50,
    total: 87,
    grade: 'A',
    credits: 3,
  },
];

export const initialFeeSummary: FeeSummary = {
  total: 125000,
  paid: 100000,
  outstanding: 25000,
  nextDueDate: '15 October 2026',
  status: 'Partial',
};

export const initialFeeBreakdowns: FeeBreakdown[] = [
  {
    id: 'FEE-2026-T1',
    title: 'Tuition Fee - Academic Year 2026-27 (Odd Sem)',
    category: 'Academic',
    total: 95000,
    paid: 95000,
    outstanding: 0,
    dueDate: '15 August 2026',
    status: 'Paid',
  },
  {
    id: 'FEE-2026-H1',
    title: 'Hostel Accommodation & Mess Charges (Term 1)',
    category: 'Hostel',
    total: 25000,
    paid: 0,
    outstanding: 25000,
    dueDate: '15 October 2026',
    status: 'Pending',
  },
  {
    id: 'FEE-2026-L1',
    title: 'Cyber Security Lab Consumables & Cloud Sandbox',
    category: 'Laboratory',
    total: 5000,
    paid: 5000,
    outstanding: 0,
    dueDate: '15 August 2026',
    status: 'Paid',
  },
];

export const initialTransactions: PaymentTransaction[] = [
  {
    transactionId: 'TXN_SBI_983104921',
    date: '12 Aug 2026, 11:24 AM',
    amount: 95000,
    paymentMode: 'Net Banking (SBI)',
    receiptNo: 'REC-2026-90412',
    description: 'Tuition Fee Odd Semester 2026-27',
    status: 'Success',
  },
  {
    transactionId: 'TXN_UPI_882019482',
    date: '14 Aug 2026, 03:45 PM',
    amount: 5000,
    paymentMode: 'UPI (Google Pay)',
    receiptNo: 'REC-2026-90518',
    description: 'Cyber Security Lab & Sandbox Fee',
    status: 'Success',
  },
];

export const initialTimetable: TimetableEntry[] = [
  // Monday
  { id: 'tt-m1', day: 'Monday', period: 1, time: '09:00 - 09:55 AM', subject: 'Cryptography & Network Security', code: '21CS201', faculty: 'Dr. Radhika M', room: 'AB-3 302' },
  { id: 'tt-m2', day: 'Monday', period: 2, time: '10:00 - 10:55 AM', subject: 'Operating Systems & Kernels', code: '21CS202', faculty: 'Prof. K. Narayanan', room: 'AB-3 302' },
  { id: 'tt-m3', day: 'Monday', period: 3, time: '11:15 - 12:10 PM', subject: 'Discrete Mathematics', code: '21MA205', faculty: 'Dr. T. Venkatraman', room: 'AB-3 302' },
  { id: 'tt-m4', day: 'Monday', period: 4, time: '01:15 - 03:15 PM', subject: 'Cyber Security Lab Practicals', code: '21CS201L', faculty: 'Dr. Radhika M', room: 'Cyber Lab 2' },
  { id: 'tt-m5', day: 'Monday', period: 5, time: '03:30 - 04:30 PM', subject: 'Library & Technical Seminar', code: 'SEM-01', faculty: 'Dept Faculty', room: 'Central Library' },

  // Tuesday
  { id: 'tt-t1', day: 'Tuesday', period: 1, time: '09:00 - 09:55 AM', subject: 'Web Technology & Modern Frameworks', code: '21CS204', faculty: 'Prof. Arjun V', room: 'AB-3 302' },
  { id: 'tt-t2', day: 'Tuesday', period: 2, time: '10:00 - 10:55 AM', subject: 'Database Management Systems', code: '21CS203', faculty: 'Dr. S. Meenakshi', room: 'AB-3 302' },
  { id: 'tt-t3', day: 'Tuesday', period: 3, time: '11:15 - 12:10 PM', subject: 'Cryptography & Network Security', code: '21CS201', faculty: 'Dr. Radhika M', room: 'AB-3 302' },
  { id: 'tt-t4', day: 'Tuesday', period: 4, time: '01:15 - 03:15 PM', subject: 'Operating Systems System Call Lab', code: '21CS202L', faculty: 'Prof. K. Narayanan', room: 'Systems Lab 1' },
  { id: 'tt-t5', day: 'Tuesday', period: 5, time: '03:30 - 04:30 PM', subject: 'Sports & Physical Activity', code: 'PED-02', faculty: 'Physical Director', room: 'Main Ground' },

  // Wednesday
  { id: 'tt-w1', day: 'Wednesday', period: 1, time: '09:00 - 09:55 AM', subject: 'Discrete Mathematics', code: '21MA205', faculty: 'Dr. T. Venkatraman', room: 'AB-3 302' },
  { id: 'tt-w2', day: 'Wednesday', period: 2, time: '10:00 - 10:55 AM', subject: 'Operating Systems & Kernels', code: '21CS202', faculty: 'Prof. K. Narayanan', room: 'AB-3 302' },
  { id: 'tt-w3', day: 'Wednesday', period: 3, time: '11:15 - 12:10 PM', subject: 'Web Technology & Modern Frameworks', code: '21CS204', faculty: 'Prof. Arjun V', room: 'AB-3 302' },
  { id: 'tt-w4', day: 'Wednesday', period: 4, time: '01:15 - 03:15 PM', subject: 'Database Query Tuning Lab', code: '21CS203L', faculty: 'Dr. S. Meenakshi', room: 'Database Lab' },
  { id: 'tt-w5', day: 'Wednesday', period: 5, time: '03:30 - 04:30 PM', subject: 'Mentorship & Class Advisor Hour', code: 'MEN-01', faculty: 'Dr. Radhika M', room: 'AB-3 302' },

  // Thursday
  { id: 'tt-th1', day: 'Thursday', period: 1, time: '09:00 - 09:55 AM', subject: 'Database Management Systems', code: '21CS203', faculty: 'Dr. S. Meenakshi', room: 'AB-3 302' },
  { id: 'tt-th2', day: 'Thursday', period: 2, time: '10:00 - 10:55 AM', subject: 'Cryptography & Network Security', code: '21CS201', faculty: 'Dr. Radhika M', room: 'AB-3 302' },
  { id: 'tt-th3', day: 'Thursday', period: 3, time: '11:15 - 12:10 PM', subject: 'Discrete Mathematics', code: '21MA205', faculty: 'Dr. T. Venkatraman', room: 'AB-3 302' },
  { id: 'tt-th4', day: 'Thursday', period: 4, time: '01:15 - 03:15 PM', subject: 'Fullstack Web App Lab', code: '21CS204L', faculty: 'Prof. Arjun V', room: 'Web Lab' },
  { id: 'tt-th5', day: 'Thursday', period: 5, time: '03:30 - 04:30 PM', subject: 'Open Elective / Technical Club', code: 'CLUB-01', faculty: 'Club Leads', room: 'Student Center' },

  // Friday
  { id: 'tt-f1', day: 'Friday', period: 1, time: '09:00 - 09:55 AM', subject: 'Operating Systems & Kernels', code: '21CS202', faculty: 'Prof. K. Narayanan', room: 'AB-3 302' },
  { id: 'tt-f2', day: 'Friday', period: 2, time: '10:00 - 10:55 AM', subject: 'Web Technology & Modern Frameworks', code: '21CS204', faculty: 'Prof. Arjun V', room: 'AB-3 302' },
  { id: 'tt-f3', day: 'Friday', period: 3, time: '11:15 - 12:10 PM', subject: 'Database Management Systems', code: '21CS203', faculty: 'Dr. S. Meenakshi', room: 'AB-3 302' },
  { id: 'tt-f4', day: 'Friday', period: 4, time: '01:15 - 03:00 PM', subject: 'Project Review & Colloquium', code: 'PRJ-201', faculty: 'Dr. Radhika M', room: 'AB-3 302' },
  { id: 'tt-f5', day: 'Friday', period: 5, time: '03:15 - 04:30 PM', subject: 'Placement Preparation & Aptitude', code: 'CIR-02', faculty: 'CIR Team', room: 'Seminar Hall 1' },
];

export const initialCertificates: CertificateRequest[] = [
  {
    id: 'CERT-2026-081',
    type: 'Bonafide Certificate',
    purpose: 'Education Loan Renewal with SBI Bank',
    appliedDate: '10 Sep 2026',
    status: 'Available',
    documentUrl: '#',
    completedDate: '12 Sep 2026',
  },
  {
    id: 'CERT-2026-104',
    type: 'Course Completion Verification',
    purpose: 'Internship Application at ISRO National Remote Sensing Centre',
    appliedDate: '24 Sep 2026',
    status: 'Verification',
  },
];

export const initialNotices: CampusNotice[] = [
  {
    id: 'NOT-2026-44',
    title: 'Mid-Semester Examinations Schedule - October 2026',
    category: 'Exam',
    date: '25 Sep 2026',
    publisher: 'Controller of Examinations (CoE)',
    content: 'The Mid-Semester Examinations for all 2nd & 3rd Year B.Tech programs will commence from October 19, 2026. Hall tickets will be downloadable via CampusOne from October 12.',
    isUrgent: true,
  },
  {
    id: 'NOT-2026-42',
    title: 'Hostel Maintenance Schedule for Water Dispensers & Filter Change',
    category: 'Hostel',
    date: '24 Sep 2026',
    publisher: 'Chief Warden Office',
    content: 'Routine UV filter cleaning and water testing across Agastya and Gargi Bhavan will be conducted on Saturday between 09:00 AM and 01:00 PM.',
    isUrgent: false,
  },
  {
    id: 'NOT-2026-39',
    title: 'Smart India Hackathon 2026 - Internal University Screening',
    category: 'Academic',
    date: '22 Sep 2026',
    publisher: 'Innovation & Incubation Council',
    content: 'Shortlisted teams for the SIH 2026 internal round must submit their revised SRS documents through the student services portal by September 28.',
    isUrgent: false,
  },
  {
    id: 'NOT-2026-38',
    title: 'Important: Semester 4 Tuition Fee Due Date Reminder',
    category: 'Administration',
    date: '20 Sep 2026',
    publisher: 'Finance Section',
    content: 'Students with outstanding balance for hostel/mess charges are requested to clear dues before 15 October 2026 to avoid late penalty.',
    isUrgent: true,
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'ntf-1',
    title: 'Complaint Update',
    description: 'Your complaint CMP-1024 has been assigned to IT Support Services.',
    message: 'Your complaint CMP-1024 has been assigned to IT Support Services.',
    date: '25 Sep 2026, 02:15 PM',
    timestamp: '25 Sep 2026, 02:15 PM',
    read: false,
    isRead: false,
    type: 'complaint',
    category: 'complaint',
    linkTab: 'complaints',
  },
  {
    id: 'ntf-2',
    title: 'Gate Pass Status',
    description: 'Your gate pass request GP-881 was approved by Dr. Radhika M.',
    message: 'Your gate pass request GP-881 was approved by Dr. Radhika M.',
    date: '21 Sep 2026, 04:30 PM',
    timestamp: '21 Sep 2026, 04:30 PM',
    read: true,
    isRead: true,
    type: 'gatepass',
    category: 'gatepass',
    linkTab: 'gatepass',
  },
  {
    id: 'ntf-3',
    title: 'Academic Notice',
    description: 'Mid-Semester Examinations schedule released by Controller of Examinations.',
    message: 'Mid-Semester Examinations schedule released by Controller of Examinations.',
    date: '25 Sep 2026, 10:00 AM',
    timestamp: '25 Sep 2026, 10:00 AM',
    read: false,
    isRead: false,
    type: 'academic',
    category: 'academic',
    linkTab: 'notices',
  },
  {
    id: 'ntf-4',
    title: 'Fee Reminder',
    description: 'Outstanding balance of ₹25,000 for Hostel charges is due on 15 Oct 2026.',
    message: 'Outstanding balance of ₹25,000 for Hostel charges is due on 15 Oct 2026.',
    date: '20 Sep 2026, 09:00 AM',
    timestamp: '20 Sep 2026, 09:00 AM',
    read: true,
    isRead: true,
    type: 'fee',
    category: 'fee',
    linkTab: 'payments',
  },
];

export const initialEvents: CampusEvent[] = [
  {
    id: 'EVT-101',
    title: 'Inter-College Football Tournament 2026',
    date: '30 Sep 2026',
    time: '04:00 PM',
    venue: 'University Main Sports Complex',
    category: 'Sports',
    registered: true,
    capacity: '16 Teams',
    organizer: 'Department of Physical Education',
  },
  {
    id: 'EVT-102',
    title: 'Campus Hackathon: CodeVibe 36-Hour Sprint',
    date: '04 Oct 2026',
    time: '09:00 AM onwards',
    venue: 'TIFAC Core Auditorium & Labs',
    category: 'Technical',
    registered: true,
    capacity: '300 Participants',
    organizer: 'Cyber Security & ACM Chapter',
  },
  {
    id: 'EVT-103',
    title: 'National Tech Symposium: CyberShield 2026',
    date: '12 Oct 2026',
    time: '10:00 AM',
    venue: 'Amriteshwari Hall',
    category: 'Symposium',
    registered: false,
    capacity: '500 Seats',
    organizer: 'School of Computing',
  },
  {
    id: 'EVT-104',
    title: 'Annual Cultural Festival: UTSAV 2026',
    date: '28 Oct 2026',
    time: '05:30 PM',
    venue: 'Open Air Amphitheatre',
    category: 'Cultural',
    registered: false,
    capacity: 'Open to All',
    organizer: 'Student Cultural Committee',
  },
];

export const initialLeaves: LeaveRequest[] = [
  {
    id: 'LV-401',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    fromDate: '02 Oct 2026',
    toDate: '03 Oct 2026',
    days: 2,
    reason: 'Attending elder sibling wedding in hometown (Chennai)',
    status: 'Pending',
    appliedOn: '25 Sep 2026',
    documentName: 'wedding_invitation_scan.pdf',
  },
  {
    id: 'LV-389',
    studentName: 'Ashwanth R',
    rollNo: '25107',
    fromDate: '12 Sep 2026',
    toDate: '13 Sep 2026',
    days: 2,
    reason: 'Viral fever rest as advised by University Health Center',
    status: 'Approved',
    appliedOn: '11 Sep 2026',
    documentName: 'medical_fitness_certificate.pdf',
  },
];

export const initialAwards: AwardItem[] = [
  {
    id: 'AWD-01',
    title: '1st Prize - University Cyber Forensics CTF',
    category: 'Technical',
    event: 'National Cyber Security Awareness Month CTF',
    date: 'March 2026',
    issuer: 'Center for Cyber Security Systems & Networks',
    position: 'Winner (Team CipherX)',
  },
  {
    id: 'AWD-02',
    title: 'Finalist - Smart India Hackathon (Hardware Edition)',
    category: 'Hackathon',
    event: 'SIH National Grand Finale',
    date: 'December 2025',
    issuer: 'Ministry of Education & AICTE',
    position: 'National Top 5 Team',
  },
  {
    id: 'AWD-03',
    title: 'Runners Up - Inter-Collegiate Football Cup',
    category: 'Sports',
    event: 'Chancellor Gold Trophy Tournament',
    date: 'February 2026',
    issuer: 'University Sports Board',
    position: '2nd Place',
  },
  {
    id: 'AWD-04',
    title: 'Dean’s Honor List (Semester 3)',
    category: 'Academic',
    event: 'Academic Excellence Award',
    date: 'January 2026',
    issuer: 'Dean of Engineering',
    position: 'SGPA 9.25 / 10.0',
  },
];

export const initialIncidents: CampusIncident[] = [
  {
    id: 'INC-2026-09',
    type: 'Electrical Maintenance',
    location: 'Academic Block 3 - 2nd Floor Corridor',
    description: 'Flickering tube light fixture with buzzing noise near Room 204.',
    reportedAt: '24 Sep 2026, 04:30 PM',
    status: 'Under Investigation',
  },
  {
    id: 'INC-2026-06',
    type: 'Campus Transport',
    location: 'North Gate Bus Bay 2',
    description: 'Route 4 evening bus arrived 25 minutes late due to tire check.',
    reportedAt: '19 Sep 2026, 06:10 PM',
    status: 'Resolved',
  },
];

export const initialRefunds: RefundRequest[] = [
  {
    id: 'REF-2026-102',
    category: 'Caution Deposit Adjustment',
    amount: 5000,
    appliedDate: '15 Sep 2026',
    status: 'Approved',
    note: 'Adjusted against mess dues statement for Semester 3.',
  },
  {
    id: 'REF-2026-094',
    category: 'Exam Revaluation Fee Refund',
    amount: 1200,
    appliedDate: '02 Aug 2026',
    status: 'Credited',
    note: 'Marks revised from B+ to A; full revaluation fee refunded to student account.',
  },
];
